build1:
	gcc testmain.c matrix.c -lm -o wenums
	./wenums hw5info
	#./wenums NoB.edgar 
flof:
	./wenums finalinfo

gaug:
	gcc integral.c -lm -o kroit
	./kroit

all:
	gcc main.c matrix.c -lm -o faytrix
	./faytrix NoB.edgar 
