build1:
	gcc testmain.c matrix.c -lm -o wenums
	./wenums hw5info
	#./wenums NoB.edgar 
flof:
	./wenums finalinfo

gaug:
	gcc integral.c -lm -o kroit
	./kroit

shosh:
	gcc testmain2.c matrix.c -lm -o hw1_212
	./hw1_212 hw5info
ech289:
	gcc t3.c matrix.c -lm -o echf
	./echf hw5info

all:
	gcc main.c matrix.c -lm -o faytrix
	./faytrix NoB.edgar 
